### ISSUE TITLE
请问这个可以正常编译出可以用的服务端吗？

### ISSUE THREAD

**Issue by surfsun** [pangliang/MirServer-Delphi#1]
如题

**Comment by pangliang** [comment]
不清楚, 应该不行, 是网上找来参考的

**Comment by surfsun** [comment]
那你有能用的源码吗？ 或者是否知道反外挂插件怎么开发？ 我想做一个反外挂的插件。

**Comment by pangliang** [comment]
https://github.com/pangliang/MirServer-Netty
http://www.zhaoxiaodan.com/java/%E7%94%A8Netty%E5%81%9A%E4%BC%A0%E5%A5%872%E6%9C%8D%E5%8A%A1%E5%99%A8-%E7%BD%91%E7%BB%9C%E9%83%A8%E5%88%86.html

**Comment by surfsun** [comment]
感谢！！！
